services:
  userservice-db:
    image: mysql:8.1
    container_name: userserviceDbContainer
    environment:
      MYSQL_ROOT_PASSWORD: Qwerty_12345
      MYSQL_DATABASE: userserviceNewDb
    ports:
      - "3303:3306"
    volumes:
      - userserviceNewDb-db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-pQwerty_12345" ]
      interval: 5s
      retries: 10
      start_period: 10s
    networks:
      - shared-net


  redis:
    image: redis:latest
    container_name: redisContainer
    ports:
      - "6379:6379"
    networks:
      - shared-net


  userservice-clean:
    build: .
    container_name: userserviceCleanContainer
    depends_on:
      userservice-db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8092:8092"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://userservice-db:3306/userserviceNewDb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Qwerty_12345
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_REDIS_HOST: redisContainer
    networks:
      - shared-net


  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloakContainer
    command: start-dev
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://userservice-db:3306/keycloakNewDb
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: Qwerty_12345
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9094:8080"
    depends_on:
      - userservice-db
    restart: always
    networks:
      - shared-net

volumes:
  userserviceNewDb-db-data:


networks:
  shared-net:
    external: true




